### ISSUE TITLE
Add tool for formatting?

### ISSUE THREAD

**Issue by abelsiqueira** [point-cloud-radar/bird-cloud-gnn#19]
Something like `yapf`, `black` or `autopep8`.

**Comment by abelsiqueira** [comment]
Looks like the options are

- `yapf`, but we have to write down some configuration;
- `black`, but we can't customize.

I would use `black` because I have some opinions on formatting, and if we use `yapf`, I would spend too long trying to customize.

**Comment by lyashevska** [comment]
Closing because #34 was created.
