### ISSUE TITLE
Check if random subsampling of nodes is feasible

### ISSUE THREAD

**Issue by lyashevska** [point-cloud-radar/bird-cloud-gnn#48]
Can be useful to reduce number of nodes

**Comment by bart1** [comment]
The testing the in the title of #62 maybe more was referring to "testing"/exploring training procedures. And not so much to the actual testing procedure

**Comment by bart1** [comment]
The suggestion is to have `RadarDataSet` to have an option to randomly select `n` points POI per label category (Stratefied random sampling).

**Comment by abelsiqueira** [comment]
Done in #91
