### ISSUE TITLE
Prospector is hanging

### ISSUE THREAD

**Issue by lyashevska** [point-cloud-radar/bird-cloud-gnn#6]
Consider moving to flake8

**Comment by lyashevska** [comment]
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
requirements-detector 1.0.3 requires packaging<22.0,>=21.3, but you have packaging 23.0 which is incompatible.
prospector 1.8.4 requires packaging<22.0, but you have packaging 23.0 which is incompatible.
```

**Comment by abelsiqueira** [comment]
https://github.com/NLeSC/python-template/issues/335 was created to track this

**Comment by abelsiqueira** [comment]
It is not hanging for me. Please provide more information about your system. I'm using Python 3.9.16 from pyenv. Prospector version 1.8.4.

**Comment by lyashevska** [comment]
Thanks. I have following versions: prospector 1.8.4 and Python 3.10.6. I will test with a different Python version from pyenv.

**Comment by lyashevska** [comment]
I can confirm that Prospector works with Python version 3.9.0 from pyenv. This issue can be closed.
