### ISSUE TITLE
Iteratively increase `max_distance` in radar_dataset

### ISSUE THREAD

**Issue by bart1** [point-cloud-radar/bird-cloud-gnn#63]
For reading the data it would be good to not omit points of interest when the `min_neighbours` is not reached. @lyashevska and me discussed that a reasonable procedure would be to increase `max_distance` iteratively until `min_neighbours` is reached. The ultimate `max_distance` should probably be 10 km as we have already omitted data beyond this.

**Comment by abelsiqueira** [comment]
This is not clear to me yet. Maybe after #66 we can discuss it further.

**Comment by bart1** [comment]
We discussed the way graphs were calculated. From this line https://github.com/point-cloud-radar/bird-cloud-gnn/blob/7c166b219f87c46003506c1425c8cf08de095a9a/bird_cloud_gnn/radar_dataset.py#L29 I get that if annotated points are in sparse regions they are more likely to be ignored. I think that is undesirable, rather it might be good to increase the `max_distance` for those points so the number of neighbors might be reached

**Comment by bart1** [comment]
If it easier we can also discuss this later in person

**Comment by bart1** [comment]
Might also relate to #88
