### ISSUE TITLE
Consider changing from sphinx/read-the-docs to mkdocs/github-pages

### ISSUE THREAD

**Issue by abelsiqueira** [point-cloud-radar/bird-cloud-gnn#65]
For these reasons:

- It is simpler to install and build (no makefile)
- It uses markdown instead of rst
- RTD is an external application that required an additional account. GitHub pages are built from the `gh-pages` branch.

**Comment by lyashevska** [comment]
Closing this issue as it will not be worked on. Sphinx/read-the-docs works fine.
