### ISSUE TITLE
Create RadarDataset from a single file

### ISSUE THREAD

**Issue by abelsiqueira** [point-cloud-radar/bird-cloud-gnn#73]

**Comment by bart1** [comment]
Can I help with this?

**Comment by abelsiqueira** [comment]
Absolutely

**Comment by lyashevska** [comment]
Can this be closed?

**Comment by abelsiqueira** [comment]
no

**Comment by bart1** [comment]
I have been playing around a little, mainly with the goal to also create a `RadarDataSet` from a pandas data.frame. This would be very helpful for evaluation purposes later as it allow to generate predictions without going through `csv`/`parquet` in the future. The `reticulate` package in R then allows for direct interaction. Similarly I guess python libraries can create pandas dataframes from radar data

I have been playing around a bit and this kind of works except for my lack of experience with variable constructors in python:
```r
library(reticulate)
use_miniconda("bird-cloud", F)
require(reticulate)
rd<-import("bird_cloud_gnn.radar_dataset")
rd$RadarDataset(d, features = names(d)[-5], target = 'target')

```

**Comment by abelsiqueira** [comment]
It would be convenient to convert directly from `pandas.DataFrame` and from a single file. I think the following is needed to make it work:

- Change the first argument of the constructor to something more generic
- Check if input is `pandas.DataFrames`, and create a `self.input_data` in that case and set `self.data_folder=None`.
- Check if input is `string`, and from there check if the input is a file or a folder. If it is a file, read the file like the beginning of the current `RadarDataset._read_one_file`. Otherwise, do what is currently done.
- Possibly create an auxiliary function to read the correct input type and replace the beginning of `_read_one_file` with that
- Create a new function `_process_data` that does the bulk of the work currently in `_read_one_file`.
- Change `process` and `_read_one_file` accordingly.

The changes look much larger - maybe in practice they won't be. Doing the work of the refactoring (last 3 point) first would probably be better.

My R knowledge is pretty much non-existent, so I can't suggest anything related to that. But I am happy that is going well.

**Comment by bart1** [comment]
If you are not working on the class I can have a look, looks like a good exercise to dust off my python

**Comment by abelsiqueira** [comment]
Please, go ahead. I don't think we have any pending major changes in the class
